version: "3.1"
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: hackathon
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
